### ISSUE TITLE
app is not handling error 500 and 404 gracefully

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#105]
I just got a 500 error while navigating http://nightly.vilfredo.org/question/4  

BTW also not handling 404's gracefully.  see http://nightly.vilfredo.org/question/7dfsfsdfs for example.

We sould have some nice pages (in the settings file we ca have a DEBUG_MODE = ON flag to show additional info about the error in the same page for developers and for usage in test and nightly setups). Like proposed in #75 check some pages that come along with that theme:
http://bucketadmin.themebucket.net/404.html
http://bucketadmin.themebucket.net/500.html

For the 500 error, the app showed me a blank page, but here is what google chrome caught:

![image](https://cloud.githubusercontent.com/assets/180794/5599737/da145332-92cc-11e4-9e11-6018a62b9e3a.png)

And here is the page response body (seems like just there was no ID 4):

```javascript
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>NoResultFound: No row was found for one() // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 49312592,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "1BNlcb1Kgx8u0zzm9mnU";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>sqlalchemy.orm.exc.NoResultFound</h1>
<div class="detail">
  <p class="errormsg">NoResultFound: No row was found for one()</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-49315472">
  <h4>File <cite class="filename">"/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py"</cite>,
      line <em class="line">1701</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-49311824">
  <h4>File <cite class="filename">"/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py"</cite>,
      line <em class="line">1689</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-49314768">
  <h4>File <cite class="filename">"/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py"</cite>,
      line <em class="line">1687</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-49312976">
  <h4>File <cite class="filename">"/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py"</cite>,
      line <em class="line">1360</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-49313488">
  <h4>File <cite class="filename">"/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py"</cite>,
      line <em class="line">1358</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-49312272">
  <h4>File <cite class="filename">"/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py"</cite>,
      line <em class="line">1344</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-49311952">
  <h4>File <cite class="filename">"/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/api.py"</cite>,
      line <em class="line">144</em>,
      in <code class="function">decorated</code></h4>
  <pre>return f(*args, **kwargs)</pre>
</div>

<li><div class="frame" id="frame-49312720">
  <h4>File <cite class="filename">"/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/api.py"</cite>,
      line <em class="line">944</em>,
      in <code class="function">api_get_questions</code></h4>
  <pre>perm = question.get_permissions(user)</pre>
</div>

<li><div class="frame" id="frame-49312528">
  <h4>File <cite class="filename">"/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/models.py"</cite>,
      line <em class="line">1433</em>,
      in <code class="function">get_permissions</code></h4>
  <pre>invite = self.invites.filter_by(receiver_id=user.id).one()</pre>
</div>

<li><div class="frame" id="frame-49311888">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py"</cite>,
      line <em class="line">2312</em>,
      in <code class="function">one</code></h4>
  <pre>raise orm_exc.NoResultFound(&quot;No row was found for one()&quot;)</pre>
</div>
</ul>
  <blockquote>NoResultFound: No row was found for one()</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/api.py", line 144, in decorated
    return f(*args, **kwargs)
  File "/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/api.py", line 944, in api_get_questions
    perm = question.get_permissions(user)
  File "/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/models.py", line 1433, in get_permissions
    invite = self.invites.filter_by(receiver_id=user.id).one()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2312, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vilfredo/env/vilfredo-nightly/lib/python2.7/site-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/api.py", line 144, in decorated
    return f(*args, **kwargs)
  File "/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/api.py", line 944, in api_get_questions
    perm = question.get_permissions(user)
  File "/home/vilfredo/nightly.vilfredo.org/vilfredo-core/VilfredoReloadedCore/models.py", line 1433, in get_permissions
    invite = self.invites.filter_by(receiver_id=user.id).one()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2312, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

-->
```

**Comment by pietrosperoni** [comment]
I am asking the question: What should we write in the 404 question, in the demo.vilfredo.org

**Comment by giovanisp** [comment]
for 2.0.0-rc1, anything. We just have to address the 404 and 500 errors. Clean the production logs at launch @derekpa.

**Comment by giovanisp** [comment]
#148 handled 404 for rc1.
Next we need for error 500 and others, likely (403, ecc...).

**Comment by derekpa** [comment]
500 already added with the 400.
